// <auto-generated />
using MaestroMunicipos.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaestroMunicipos.Migrations
{
    [DbContext(typeof(MaestroMunicipiosContext))]
    [Migration("20190516001127_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MaestroMunicipos.Model.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<int>("PaisId");

                    b.HasKey("DepartamentoId");

                    b.HasIndex("PaisId");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("MaestroMunicipos.Model.Municipio", b =>
                {
                    b.Property<int>("MunicipioId");

                    b.Property<int>("DepartamentoId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("MunicipioId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Municipio");
                });

            modelBuilder.Entity("MaestroMunicipos.Model.Pais", b =>
                {
                    b.Property<int>("PaisId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("PaisId");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("MaestroMunicipos.Model.Departamento", b =>
                {
                    b.HasOne("MaestroMunicipos.Model.Pais", "Pais")
                        .WithMany("Departamentos")
                        .HasForeignKey("PaisId")
                        .HasConstraintName("FK_Departamento_Pais");
                });

            modelBuilder.Entity("MaestroMunicipos.Model.Municipio", b =>
                {
                    b.HasOne("MaestroMunicipos.Model.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .HasConstraintName("FK_Municipio_Departamento");
                });
#pragma warning restore 612, 618
        }
    }
}
